version: "1.29"

services:

  accounts:
    image: account-service-image:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - eazybank-network

  loans:
    image: loan-service-image:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - eazybank-network

  cards:
    image: card-service-image:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - eazybank-network

networks:
  eazybank-network: